#!/bin/python3
import sys
import requests

PISTON_URL = 'http://127.0.0.1:2005/api/v2/piston/execute'
LANGUAGE = sys.argv[1]
SOURCE_CODE_FILE = open(sys.argv[2])
SOURCE_CODE = SOURCE_CODE_FILE.read()
SOURCE_CODE_FILE.close()
VERSION = sys.argv[3] if len(sys.argv) >= 4 else '*'
RUNTIME = sys.argv[4] if len(sys.argv) >= 5 else None

response = requests.post(PISTON_URL, json={
    'language': LANGUAGE,
    'version': VERSION,
    'runtime': RUNTIME,
    'files': [{ 'content': SOURCE_CODE }],
    'compile_timeout': 3000,
    'run_timeout': 1000
})

print(response.headers)
print()
print(response.json())
