#!/bin/python3
import sys
import requests

PISTON_URL = 'http://127.0.0.1:2000/api/v2/execute'
LANGUAGE = sys.argv[1]
SOURCE_CODE_FILE = open(sys.argv[2])
SOURCE_CODE = SOURCE_CODE_FILE.read()
SOURCE_CODE_FILE.close()
VERSION = '*'

response = requests.post(PISTON_URL, json={
    'language': LANGUAGE,
    'version': '*',
    'files': [{ 'content': SOURCE_CODE }]
})

print(response.json())
