#!/bin/python3
import sys
import requests
import json

PISTON_URL = 'http://127.0.0.1:2000/api/v2/execute'
FILE_NAME = sys.argv[1]
SOURCE_CODE_FILE = open(FILE_NAME)
LANGUAGE = FILE_NAME.split('.')[1]
SOURCE_CODE = SOURCE_CODE_FILE.read()
SOURCE_CODE_FILE.close()
VERSION = sys.argv[2] if len(sys.argv) >= 3 else '*'
RUNTIME = sys.argv[3] if len(sys.argv) >= 4 else None

response = requests.post(PISTON_URL, json={
    'language': LANGUAGE,
    'version': VERSION,
    'runtime': RUNTIME,
    'files': [{'content': SOURCE_CODE}],
    'packages': ["pandas"]
})

print(json.dumps(response.json(), indent=4).replace('\\n', '\n'))
