#!/bin/python3
import asyncio
import websockets
import json
import sys

URL = 'ws://127.0.0.1:2000/api/v2/connect'
LANGUAGE = sys.argv[1]
SOURCE_CODE = open(sys.argv[2]).read()
JSON_DICT = {
    'type': 'init',
    'language': LANGUAGE,
    'version': '*',
    'files': [{ 'content': SOURCE_CODE }]
}
JSON = json.dumps(JSON_DICT)

async def run():
    async with websockets.connect(URL) as websocket:
        await websocket.send(JSON)

asyncio.run(run())
