#!/bin/python3
import sys
import requests

PISTON_URL = 'http://127.0.0.1:2000/api/v3/execute'
RUNTIME_ID = int(sys.argv[1])
SOURCE_CODE_FILE = open(sys.argv[2])
SOURCE_CODE = SOURCE_CODE_FILE.read()
SOURCE_CODE_FILE.close()
VERSION = '*'

response = requests.post(PISTON_URL, json={
    'runtime_id': RUNTIME_ID,
    'version': '*',
    'stdin': 'hello',
    'files': [{ 'content': SOURCE_CODE }]
})

print(response.json())
