#!/bin/python3
import asyncio
import websockets
import json
import sys

URL = 'ws://127.0.0.1:2000/api/v3/connect'
RUNTIME_ID = int(sys.argv[1])
SOURCE_CODE = open(sys.argv[2]).read()
JSON_DICT = {
    'type': 'init',
    'runtime_id': RUNTIME_ID,
    'files': [{ 'content': SOURCE_CODE }]
}
JSON = json.dumps(JSON_DICT)

async def run():
    async with websockets.connect(URL) as websocket:
        await websocket.send(JSON)
        while True:
            msg = await websocket.recv()
            print(msg)

asyncio.run(run())
